export const DEVICE_SOURCES = {
  KOBITON: 'KOBITON',
  SAUCE_LABS: 'SAUCE_LABS'
}

export const PRESS_TYPES = {
  HOME: 'HOME',
  BACK: 'BACK',
  POWER: 'POWER',
  APP_SWITCH: 'APP_SWITCH',
  ENTER: 'ENTER',
  DELETE: 'DELETE'
}
