name: CI

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]

permissions:
  checks: write

jobs:
  run-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v3
        with:
          node-version: 20.10.0

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile --non-interactive

      - name: Lint
        run: |
          yarn lint

  run-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v3
        with:
          node-version: 20.10.0

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile --non-interactive

      - name: Test
        run: |
          yarn test
